import type {
  SiteSettings,
  Hero,
  About,
  Skill,
  Project,
  Experience,
  Education,
  Service,
  Certification,
  SocialLink,
} from "@/types/database";

export const fallbackData = {
  siteSettings: {
    id: "default",
    site_name: "Md Moklesar Rahman",
    owner_name: "Md Moklesar Rahman",
    tagline: "Web Designer & Developer",
    logo_url: null,
    resume_url: "/files/Md_Moklesar_Rahman.pdf",
    primary_email: "md.moklasarrahmanbappy@gmail.com",
    phone: "+880-161-6322779",
    location: "Ramnogor Mor, Dinajpur-5200, Bangladesh",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  } as SiteSettings,

  hero: {
    id: "default",
    title: "Md Moklesar Rahman",
    subtitle: "Web Designer & Developer",
    description:
      "Architect of custom WordPress themes and Laravel dashboards, blending modular UI/UX with joyful polish.",
    profile_image_url: null,
    background_image_url: null,
    cta_primary_label: "Hire Me",
    cta_primary_url: "#contact",
    cta_secondary_label: "Download CV",
    cta_secondary_url: "/files/Md_Moklesar_Rahman.pdf",
    is_active: true,
    updated_at: new Date().toISOString(),
  } as Hero,

  about: {
    id: "default",
    heading: "About Me",
    content:
      "I am a passionate Web Designer & Developer with experience building custom WordPress themes, Laravel dashboards, and modern web applications. Currently serving as an Assistant Maintenance Engineer at the Land Record & Survey Directorate, Dhaka. I blend modular UI/UX design with clean code to create joyful digital experiences.",
    image_url: null,
    years_experience: 5,
    updated_at: new Date().toISOString(),
  } as About,

  skills: [
    { id: "1", name: "WordPress", category: "development", level: 85, icon: "fa-brands fa-wordpress", icon_url: null, sort_order: 1, is_visible: true, created_at: "", updated_at: "" },
    { id: "2", name: "Web Development", category: "development", level: 80, icon: "fa-solid fa-globe", icon_url: null, sort_order: 2, is_visible: true, created_at: "", updated_at: "" },
    { id: "3", name: "Web Design", category: "design", level: 75, icon: "fa-solid fa-pen-ruler", icon_url: null, sort_order: 3, is_visible: true, created_at: "", updated_at: "" },
    { id: "4", name: "Graphics Design", category: "design", level: 70, icon: "fa-solid fa-palette", icon_url: null, sort_order: 4, is_visible: true, created_at: "", updated_at: "" },
    { id: "5", name: "Laravel", category: "development", level: 70, icon: "fa-brands fa-laravel", icon_url: null, sort_order: 5, is_visible: true, created_at: "", updated_at: "" },
    { id: "6", name: "HTML/CSS", category: "development", level: 90, icon: "fa-brands fa-html5", icon_url: null, sort_order: 6, is_visible: true, created_at: "", updated_at: "" },
    { id: "7", name: "JavaScript", category: "development", level: 75, icon: "fa-brands fa-js", icon_url: null, sort_order: 7, is_visible: true, created_at: "", updated_at: "" },
    { id: "8", name: "PHP", category: "development", level: 75, icon: "fa-brands fa-php", icon_url: null, sort_order: 8, is_visible: true, created_at: "", updated_at: "" },
  ] as Skill[],

  projects: [] as Project[],

  experience: [
    {
      id: "1",
      company: "Pentagon International Limited",
      position: "Sr. WordPress Developer",
      start_date: "2022-07-01",
      end_date: "2023-11-30",
      is_current: false,
      description: "Senior WordPress developer building custom themes and plugins for enterprise clients.",
      location: "Rangs Nasim Square, 275/D, Suite #C12, Lift Level-11, Rd No. 27, Dhaka 1207",
      sort_order: 1,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "2",
      company: "Azmaain Corporation",
      position: "WordPress Developer",
      start_date: "2020-03-01",
      end_date: "2022-06-15",
      is_current: false,
      description: "WordPress development, theme customization, and client project delivery.",
      location: "Rangs Nasim Square, 275/D, Suite #C12, Lift Level-11, Rd No. 27, Dhaka 1207",
      sort_order: 2,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "3",
      company: "Enigma IT Solution",
      position: "Jr. Web Designer",
      start_date: "2019-01-06",
      end_date: "2020-02-28",
      is_current: false,
      description: "Web design and front-end development for various client projects.",
      location: "85/A Eskaton Palace, New Eskaton Road, Banglamotor, Dhaka-1000",
      sort_order: 3,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
  ] as Experience[],

  education: [
    {
      id: "1",
      institution: "Daffodil International University",
      degree: "Bachelor of Science (B.Sc)",
      field: "Computer Science & Engineering",
      start_year: 2014,
      end_year: 2019,
      description: null,
      sort_order: 1,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "2",
      institution: "Queen's School & College",
      degree: "Higher Secondary Certificate (HSC)",
      field: "Science",
      start_year: 2012,
      end_year: 2014,
      description: null,
      sort_order: 2,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "3",
      institution: "K.B.M. Collegiate High School",
      degree: "Secondary School Certificate (SSC)",
      field: "Science",
      start_year: 2010,
      end_year: 2012,
      description: null,
      sort_order: 3,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
  ] as Education[],

  services: [
    {
      id: "1",
      title: "Graphics Design",
      description: "Creating compelling brand identities, logos, and visual assets that communicate your brand story effectively.",
      icon: "palette",
      category: "graphics-design",
      sort_order: 1,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "2",
      title: "Web Design",
      description: "Designing modern, responsive, and user-friendly websites with clean aesthetics and intuitive navigation.",
      icon: "monitor",
      category: "web-design",
      sort_order: 2,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "3",
      title: "Web Development",
      description: "Building robust, scalable web applications using modern frameworks and best coding practices.",
      icon: "code",
      category: "web-development",
      sort_order: 3,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "4",
      title: "WordPress",
      description: "Custom WordPress themes, plugins, and full website solutions tailored to your business needs.",
      icon: "layout",
      category: "wordpress",
      sort_order: 4,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
  ] as Service[],

  certifications: [] as Certification[],

  socialLinks: [
    {
      id: "1",
      platform: "Instagram",
      url: "https://www.instagram.com/mr.bappy2/",
      icon: "instagram",
      sort_order: 1,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "2",
      platform: "YouTube",
      url: "https://www.youtube.com/@LotsofLaugh-lol",
      icon: "youtube",
      sort_order: 2,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "3",
      platform: "GitHub",
      url: "https://github.com/Md-Moklesar-Rahman-Bappy",
      icon: "github",
      sort_order: 3,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
    {
      id: "4",
      platform: "LinkedIn",
      url: "https://www.linkedin.com/in/md-moklasar-rahman-bappy",
      icon: "linkedin",
      sort_order: 4,
      is_visible: true,
      created_at: "",
      updated_at: "",
    },
  ] as SocialLink[],
};
